development:
  adapter: async
  url: redis://localhost:6379

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Buddy_Up_api_production


